name: expandable_bottom_sheet
description: This is a BottomSheet with a draggable height like the Google Maps App on Android.
version: 0.2.1+1
author: Torben Keller <torben.keller.develop@gmail.com>
homepage: https://github.com/torbenkeller/expandable_bottom_sheet

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: